camel:
  springboot:
    name: Geocoder
  rest:
    component: servlet
    port: 8080
    host: localhost
    context-path: /camel
    enable-cors: true
    binding-mode: json
    data-format-property:
      prettyPrint: true
    api-context-path: /api-doc
    api-property:
#      cors: true
      api:
        title: Geocoder API
        version: 1.0.0
